### ISSUE TITLE
xpath_node_set' object is not iterable

### ISSUE THREAD

**Issue by ShelleyLake** [semigodking/pugi#2]
@semigodking  I've tried again but I don't go that far.
I would like to use pugixml to execute xpath queries, but somehow the structure that I need is not iterable and the operator [] is not exported to python (which is supported according to the pugixml documentation).

```
import pugi
file = r'D:\SB\Downloads\20191024085351-40142-data.xml'

doc = pugi.xml_document()
result = doc.load_file(file)

if result is not None:
  for it in doc.select_nodes("//node"):
    it
```

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: 'xpath_node_set' object is not iterable
```

Could you give me an hint how to modify the pugi.i file to make 'xpath_node_set' iterable or how to add the [] operator?

**Comment by ShelleyLake** [comment]
During the compilation process I get quite a lot of warnings, among those (probably) the reason of the missing operator []

> .\pugixml\src\pugixml.hpp(741) : Warning 361: operator! ignored
> .\pugixml\src\pugixml.hpp(793) : Warning 362: operator= ignored
> .\pugixml\src\pugixml.hpp(846) : Warning 383: operator++ ignored
> .\pugixml\src\pugixml.hpp(849) : Warning 384: operator-- ignored
> .\pugixml\src\pugixml.hpp(1329) : Warning 361: operator! ignored
> .\pugixml\src\pugixml.hpp(1371) : Warning 362: operator= ignored
> .\pugixml\src\pugixml.hpp(1386) : Warning 389: operator[] ignored (consider using %extend)

**Comment by semigodking** [comment]
I am not able to help on this as I am not good at SWIG.
You may need to figure it out by looking into SWIG doc.

Shelley Lake <notifications@github.com> 于 2019年10月25日周五 02:35写道：
